### ISSUE TITLE
Should Slackware deserve a spot somewhere?

### ISSUE THREAD

**Issue by DerRoteVogel** [r-PlaceTux/place_tux#45]
I have been wondering if Slackware should be on the placetux image, since it's ground to many other linux distros and is still running for 29 years!

**Comment by Epikest** [comment]
> I have been wondering if Slackware should be on the placetux image, since it's ground to many other linux distros and is still running for 29 years!

we have slackware, it's above arch

**Comment by DerRoteVogel** [comment]
> > I have been wondering if Slackware should be on the placetux image, since it's ground to many other linux distros and is still running for 29 years!
> 
> we have slackware, it's above arch

I see, i didn't notice it because its purple, not black.
Furthermore the underline isn't one space apart from the big "S".

**Comment by Epikest** [comment]
we tried to make it look good with the space we have. we don't have an outer circle so that's why it's purple. and if you take a closer look at the real slackware logo, you can see that the S isn't completely black.
